name: 'daily-report'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 22 * * *' # 国际标准时间 早上 6点半

jobs:
  daily-email:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        # uses: Selects an action to run as part of a step in your job. An action is a reusable unit of code. You can use an action defined in the same repository as the workflow, a public repository, or in a published Docker container image.
        uses: actions/checkout@v2 
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests pandas
      - name: 'action-get-weather'
        run: python report-weather.py
      - name: 'action-get-hot-topics'
        run: python report-hot-topics.py
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master # 使用别人已经写好的 action
        with:
          server_address: smtp.yandex.com # yandex 不需要认证，yandex 是俄罗斯最受欢迎的邮箱服务
          server_port: 465
          username: ${{ secrets.MAIL_YANDEX_USERNAME }}
          password: ${{ secrets.MAIL_YANDEX_PASSWD }}
          subject: Daily Report
          body: file://report.html
          to:  ${{ secrets.QQMAIL }} #, ${{ secrets.GMAIL }}
          from: GitHub Actions
          content_type: text/html
