name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Nanjing' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.live.com
          server_port: 465
          username: ${{ secrets.HOTMAIL_USERNAME }}
          password: ${{ secrets.HOTMAIL_PASSWD }}
          subject: Nanjing Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: wanshojs@gmail.com
          from: GitHub Actions
          content_type: text/html